### PR TITLE
Implement neighbourhood and cube coordinate validation

### PR DESCRIPTION
**Pull request by approaching236**
I added some issues that describe what I'm trying to address here. Mostly I just wanted the neighourhood method that would return the hexes within a distance of a hex. When I was looking into that I found that the Hex type accepted data that wasn't correct. This is also making me think that maybe it would be a good idea to only create a new hex with the new function rather than the `%Hex{q: q, r: r, s: s}` syntax

### CODE REVIEW

**Comment by approaching236** [comment]
I don't see it described in that website, but if you do want to keep those valid indexes, there should likely be a cheap equivalence class function that you could use to 'simplify' the coordinate. You can do something similar with rotations like 360 degrees from north is still north. Three turns left is the same as one right, etc. Something something modulo

**Comment by rayalex** [comment]
Hey, thanks for the PR.

Yes, is seems that I have (somehow) missed the obvious problem with invalid coordinates. 😄 

I would propose we make just one additional change to the `new/3`, to make it more Elixir idiomatic:

- Rename `new/3` to `new!/3`, in order to make it obvious it could `raise`.
- Make `new/3` return `{:ok, hex}` or `{:error, string}` in case invalid coordinates have been supplied.

This would unfortunately break backwards compatibility but I can push the change as a major version update. 

Thoughts?  

Also, I agree that `Hex` struct should probably be made `@opaque`

**Comment by approaching236** [comment]
ok, rad. Imma make those two new!/3 and new/3 with the api you've described. Sounds correct. I'm not usually fond of creating breaking changes like that, but this seems like a very reasonable update to the api based on a bug that we've discovered. The idea of adding in an equivalence class would prevent this whole issue, but probably doesn't make a whole lot of sense / would actually probably confuse folks when they try to make a hex with certain coordinates, then everything changes out from under them.

I wasn't sure how to address the Hex struct situation, but I'll look into what it means for something to be `@opaque`, it's probably the idea that I was trying to express.

**Comment by rayalex** [comment]
Merged 👍 

I'll release `2.0.0` tomorrow - need to make sure docs are up to date and look into some minor things.

**Comment by rayalex** [comment]
Release 2.0.0 is now available on Hex PM.

**Pull request merged**
